version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_sklad_net

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - my_sklad_net
    depends_on:
      - redis

  celery_worker:
    build: .
    command: /app/.venv/bin/celery -A celery_worker worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - my_sklad_net
    depends_on:
      - redis

networks:
  my_sklad_net:
    driver: bridge
