version: '3.8'

services:
  redis:
    image: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=1024
      - vm.overcommit_memory=1
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - my_sklad_net

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - my_sklad_net
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  celery_worker:
    build: .
    command: ["./wait-for-redis.sh", "redis", "celery", "-A", "celery_worker", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    networks:
      - my_sklad_net
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

networks:
  my_sklad_net:
    driver: bridge

